# Generated by Django 4.2.30 on 2026-04-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='upi_id',
            field=models.CharField(blank=True, help_text='e.g. yourname@paytm', max_length=50),
        ),
    ]
