# Generated by Django 5.0.14 on 2026-04-17 12:36

from django.db import migrations, models
from django.utils.text import slugify


def populate_business_slugs(apps, schema_editor):
    Business = apps.get_model('users', 'Business')
    seen = set()
    for business in Business.objects.all().order_by('id'):
        base_slug = slugify(business.name) or 'business'
        slug = base_slug
        index = 1
        while slug in seen:
            index += 1
            slug = f'{base_slug}-{index}'
        seen.add(slug)
        business.slug = slug
        business.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_business_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(populate_business_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
