# Generated by Django 5.0.14 on 2026-04-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_business_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='hero_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='hero_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='map_embed_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='public_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='business',
            name='public_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='business',
            name='public_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='testimonial_author',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='business',
            name='testimonial_quote',
            field=models.TextField(blank=True),
        ),
    ]
