# Generated by Django 5.0.14 on 2026-04-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_business_hero_image_url_business_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='profile_setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
