# Generated by Django 4.2.30 on 2026-07-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_business_profile_setup_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='listing_plan',
            field=models.CharField(choices=[('free', 'Free Plan'), ('pro', 'Pro Plan'), ('premium', 'Premium Plan')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='website_url',
            field=models.URLField(blank=True, help_text='Public business website'),
        ),
    ]
