# Generated by Django 4.2.30 on 2026-07-15 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_listing_plan_website_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='assigned_partners',
            field=models.ManyToManyField(blank=True, related_name='assigned_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('marketing_partner', 'Marketing Partner'), ('business', 'Business'), ('client', 'Client')], db_index=True, default='business', max_length=32),
        ),
        migrations.AlterField(
            model_name='business',
            name='industry_type',
            field=models.CharField(choices=[('salon', 'Salon / Parlour'), ('spa', 'Spa & Wellness'), ('grooming', 'Barbershop / Grooming'), ('dentist', 'Dentist Clinic'), ('clinic', 'Clinic / Doctor'), ('optical', 'Optical Shop'), ('physiotherapy', 'Physiotherapy'), ('ayurveda', 'Ayurveda / Homeopathy'), ('gym', 'Gym / Fitness Studio'), ('yoga', 'Yoga / Pilates'), ('restaurant', 'Restaurant / Café'), ('bakery', 'Bakery / Sweet Shop'), ('grocery', 'Grocery / Kirana'), ('fashion', 'Fashion / Boutique'), ('pet', 'Pet Shop / Clinic'), ('auto', 'Auto Service / Garage'), ('laundry', 'Laundry / Dry Clean'), ('tailoring', 'Tailor / Alterations'), ('home_services', 'Home Services'), ('photography', 'Photography / Studio'), ('coaching', 'Coaching / Tuition'), ('events', 'Events / Wedding'), ('legal', 'Legal / CA / Consultant'), ('realestate', 'Real Estate'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='listing_plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('premium', 'Premium')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='users.business'),
        ),
    ]
