# Generated by Django 4.2.30 on 2026-07-17 11:32
# Idempotent: indexes may already exist on prod from a prior partial apply.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_platform_roles_and_enquiries"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="business",
                    index=models.Index(
                        fields=["industry_type"],
                        name="users_busin_industr_766314_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="business",
                    index=models.Index(
                        fields=["profile_setup_completed"],
                        name="users_busin_profile_d56c1a_idx",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        'CREATE INDEX IF NOT EXISTS "users_busin_industr_766314_idx" ON "users_business" ("industry_type");',
                        'CREATE INDEX IF NOT EXISTS "users_busin_profile_d56c1a_idx" ON "users_business" ("profile_setup_completed");',
                    ],
                    reverse_sql=[
                        'DROP INDEX IF EXISTS "users_busin_industr_766314_idx";',
                        'DROP INDEX IF EXISTS "users_busin_profile_d56c1a_idx";',
                    ],
                ),
            ],
        ),
    ]
