# Generated by Django 4.2.30 on 2026-07-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_platform_roles_and_enquiries'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['industry_type'], name='users_busin_industr_766314_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['profile_setup_completed'], name='users_busin_profile_d56c1a_idx'),
        ),
    ]
