# Generated by Django 4.2.30 on 2026-07-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_business_users_busin_industr_766314_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Custom meta description (≤160 chars). Leave blank for auto.', max_length=160),
        ),
        migrations.AddField(
            model_name='business',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords. Leave blank for auto.', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Custom <title> / og:title (≤70 chars). Leave blank for auto.', max_length=70),
        ),
    ]
