# Generated by Django 4.2.30 on 2026-07-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_platform_roles_and_enquiries'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['business', 'status'], name='leads_enqui_busines_366c50_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['client', 'status'], name='leads_enqui_client__40ded6_idx'),
        ),
    ]
