# Generated by Django 4.2.30 on 2026-07-17 11:32
# Idempotent: indexes may already exist on prod from a prior partial apply.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_platform_roles_and_enquiries"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="enquiry",
                    index=models.Index(
                        fields=["business", "status"],
                        name="leads_enqui_busines_366c50_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="enquiry",
                    index=models.Index(
                        fields=["client", "status"],
                        name="leads_enqui_client__40ded6_idx",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        'CREATE INDEX IF NOT EXISTS "leads_enqui_busines_366c50_idx" ON "leads_enquiry" ("business_id", "status");',
                        'CREATE INDEX IF NOT EXISTS "leads_enqui_client__40ded6_idx" ON "leads_enquiry" ("client_id", "status");',
                    ],
                    reverse_sql=[
                        'DROP INDEX IF EXISTS "leads_enqui_busines_366c50_idx";',
                        'DROP INDEX IF EXISTS "leads_enqui_client__40ded6_idx";',
                    ],
                ),
            ],
        ),
    ]
