# Generated by Django 4.2.30 on 2026-07-17 11:32
# Idempotent: indexes may already exist on prod from a prior partial apply.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="invoice",
                    index=models.Index(
                        fields=["business", "status", "created_at"],
                        name="billing_inv_busines_9cef66_idx",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        'CREATE INDEX IF NOT EXISTS "billing_inv_busines_9cef66_idx" ON "billing_invoice" ("business_id", "status", "created_at");',
                    ],
                    reverse_sql=[
                        'DROP INDEX IF EXISTS "billing_inv_busines_9cef66_idx";',
                    ],
                ),
            ],
        ),
    ]
