# Generated by Django 4.2.30 on 2026-07-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['business', 'status', 'created_at'], name='billing_inv_busines_9cef66_idx'),
        ),
    ]
