# Generated by Django 4.2.30 on 2026-07-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['business', 'date'], name='booking_app_busines_db2e90_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['business', 'status'], name='booking_app_busines_bc09fd_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['business', 'created_at'], name='booking_app_busines_dd0f88_idx'),
        ),
    ]
