# Generated by Django 4.2.30 on 2026-07-17 11:32
# Idempotent: indexes may already exist on prod from a prior partial apply.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="appointment",
                    index=models.Index(
                        fields=["business", "date"],
                        name="booking_app_busines_db2e90_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="appointment",
                    index=models.Index(
                        fields=["business", "status"],
                        name="booking_app_busines_bc09fd_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="appointment",
                    index=models.Index(
                        fields=["business", "created_at"],
                        name="booking_app_busines_dd0f88_idx",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        'CREATE INDEX IF NOT EXISTS "booking_app_busines_db2e90_idx" ON "booking_appointment" ("business_id", "date");',
                        'CREATE INDEX IF NOT EXISTS "booking_app_busines_bc09fd_idx" ON "booking_appointment" ("business_id", "status");',
                        'CREATE INDEX IF NOT EXISTS "booking_app_busines_dd0f88_idx" ON "booking_appointment" ("business_id", "created_at");',
                    ],
                    reverse_sql=[
                        'DROP INDEX IF EXISTS "booking_app_busines_db2e90_idx";',
                        'DROP INDEX IF EXISTS "booking_app_busines_bc09fd_idx";',
                        'DROP INDEX IF EXISTS "booking_app_busines_dd0f88_idx";',
                    ],
                ),
            ],
        ),
    ]
