# Generated by Django 4.2.30 on 2026-07-17 11:32
# Idempotent: indexes may already exist on prod from a prior partial apply.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="customer",
                    index=models.Index(
                        fields=["business", "phone"],
                        name="crm_custome_busines_5343ce_idx",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        'CREATE INDEX IF NOT EXISTS "crm_custome_busines_5343ce_idx" ON "crm_customer" ("business_id", "phone");',
                    ],
                    reverse_sql=[
                        'DROP INDEX IF EXISTS "crm_custome_busines_5343ce_idx";',
                    ],
                ),
            ],
        ),
    ]
