# Generated by Django 4.2.30 on 2026-07-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business', 'phone'], name='crm_custome_busines_5343ce_idx'),
        ),
    ]
