# Generated by Django 4.2.30 on 2026-04-17 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='users.business'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.servicecategory'),
        ),
        migrations.AddField(
            model_name='businesshours',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='users.business'),
        ),
        migrations.AlterUniqueTogether(
            name='businesshours',
            unique_together={('business', 'day_of_week')},
        ),
    ]
